/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nmpc_planner_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};

/* nmpc_planner_expl_ode_hess:(i0[4],i1[4x4],i2[4x2],i3[4],i4[2],i5[6])->(o0[6],o1[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=sin(a0);
  a2=arg[3]? arg[3][1] : 0;
  a1=(a1*a2);
  a3=cos(a0);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3*a4);
  a1=(a1+a3);
  if (res[0]!=0) res[0][2]=a1;
  a1=cos(a0);
  a3=arg[0]? arg[0][2] : 0;
  a5=(a3*a2);
  a6=(a1*a5);
  a7=sin(a0);
  a3=(a3*a4);
  a8=(a7*a3);
  a6=(a6-a8);
  if (res[0]!=0) res[0][3]=a6;
  a6=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][4]=a6;
  a6=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][5]=a6;
  a6=arg[1]? arg[1][2] : 0;
  a8=cos(a0);
  a9=arg[1]? arg[1][3] : 0;
  a10=(a8*a9);
  a10=(a2*a10);
  a11=sin(a0);
  a12=(a11*a9);
  a12=(a4*a12);
  a10=(a10-a12);
  a12=(a6*a10);
  a13=(a2*a6);
  a13=(a1*a13);
  a14=sin(a0);
  a15=(a14*a9);
  a15=(a5*a15);
  a13=(a13-a15);
  a0=cos(a0);
  a15=(a0*a9);
  a15=(a3*a15);
  a6=(a4*a6);
  a6=(a7*a6);
  a15=(a15+a6);
  a13=(a13-a15);
  a9=(a9*a13);
  a12=(a12+a9);
  if (res[1]!=0) res[1][0]=a12;
  a12=arg[1]? arg[1][6] : 0;
  a9=(a12*a10);
  a15=arg[1]? arg[1][7] : 0;
  a6=(a15*a13);
  a9=(a9+a6);
  if (res[1]!=0) res[1][1]=a9;
  a9=arg[1]? arg[1][10] : 0;
  a6=(a9*a10);
  a16=arg[1]? arg[1][11] : 0;
  a17=(a16*a13);
  a6=(a6+a17);
  if (res[1]!=0) res[1][2]=a6;
  a6=arg[1]? arg[1][14] : 0;
  a17=(a6*a10);
  a18=arg[1]? arg[1][15] : 0;
  a19=(a18*a13);
  a17=(a17+a19);
  if (res[1]!=0) res[1][3]=a17;
  a17=arg[2]? arg[2][2] : 0;
  a19=(a17*a10);
  a20=arg[2]? arg[2][3] : 0;
  a21=(a20*a13);
  a19=(a19+a21);
  if (res[1]!=0) res[1][4]=a19;
  a19=arg[2]? arg[2][6] : 0;
  a10=(a19*a10);
  a21=arg[2]? arg[2][7] : 0;
  a13=(a21*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][5]=a10;
  a10=(a8*a15);
  a10=(a2*a10);
  a13=(a11*a15);
  a13=(a4*a13);
  a10=(a10-a13);
  a13=(a12*a10);
  a22=(a2*a12);
  a22=(a1*a22);
  a23=(a14*a15);
  a23=(a5*a23);
  a22=(a22-a23);
  a23=(a0*a15);
  a23=(a3*a23);
  a12=(a4*a12);
  a12=(a7*a12);
  a23=(a23+a12);
  a22=(a22-a23);
  a15=(a15*a22);
  a13=(a13+a15);
  if (res[1]!=0) res[1][6]=a13;
  a13=(a9*a10);
  a15=(a16*a22);
  a13=(a13+a15);
  if (res[1]!=0) res[1][7]=a13;
  a13=(a6*a10);
  a15=(a18*a22);
  a13=(a13+a15);
  if (res[1]!=0) res[1][8]=a13;
  a13=(a17*a10);
  a15=(a20*a22);
  a13=(a13+a15);
  if (res[1]!=0) res[1][9]=a13;
  a10=(a19*a10);
  a22=(a21*a22);
  a10=(a10+a22);
  if (res[1]!=0) res[1][10]=a10;
  a10=(a8*a16);
  a10=(a2*a10);
  a22=(a11*a16);
  a22=(a4*a22);
  a10=(a10-a22);
  a22=(a9*a10);
  a13=(a2*a9);
  a13=(a1*a13);
  a15=(a14*a16);
  a15=(a5*a15);
  a13=(a13-a15);
  a15=(a0*a16);
  a15=(a3*a15);
  a9=(a4*a9);
  a9=(a7*a9);
  a15=(a15+a9);
  a13=(a13-a15);
  a16=(a16*a13);
  a22=(a22+a16);
  if (res[1]!=0) res[1][11]=a22;
  a22=(a6*a10);
  a16=(a18*a13);
  a22=(a22+a16);
  if (res[1]!=0) res[1][12]=a22;
  a22=(a17*a10);
  a16=(a20*a13);
  a22=(a22+a16);
  if (res[1]!=0) res[1][13]=a22;
  a10=(a19*a10);
  a13=(a21*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][14]=a10;
  a10=(a8*a18);
  a10=(a2*a10);
  a13=(a11*a18);
  a13=(a4*a13);
  a10=(a10-a13);
  a13=(a6*a10);
  a22=(a2*a6);
  a22=(a1*a22);
  a16=(a14*a18);
  a16=(a5*a16);
  a22=(a22-a16);
  a16=(a0*a18);
  a16=(a3*a16);
  a6=(a4*a6);
  a6=(a7*a6);
  a16=(a16+a6);
  a22=(a22-a16);
  a18=(a18*a22);
  a13=(a13+a18);
  if (res[1]!=0) res[1][15]=a13;
  a13=(a17*a10);
  a18=(a20*a22);
  a13=(a13+a18);
  if (res[1]!=0) res[1][16]=a13;
  a10=(a19*a10);
  a22=(a21*a22);
  a10=(a10+a22);
  if (res[1]!=0) res[1][17]=a10;
  a10=(a8*a20);
  a10=(a2*a10);
  a22=(a11*a20);
  a22=(a4*a22);
  a10=(a10-a22);
  a22=(a17*a10);
  a13=(a2*a17);
  a13=(a1*a13);
  a18=(a14*a20);
  a18=(a5*a18);
  a13=(a13-a18);
  a18=(a0*a20);
  a18=(a3*a18);
  a17=(a4*a17);
  a17=(a7*a17);
  a18=(a18+a17);
  a13=(a13-a18);
  a20=(a20*a13);
  a22=(a22+a20);
  if (res[1]!=0) res[1][18]=a22;
  a10=(a19*a10);
  a13=(a21*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][19]=a10;
  a8=(a8*a21);
  a8=(a2*a8);
  a11=(a11*a21);
  a11=(a4*a11);
  a8=(a8-a11);
  a8=(a19*a8);
  a2=(a2*a19);
  a1=(a1*a2);
  a14=(a14*a21);
  a5=(a5*a14);
  a1=(a1-a5);
  a0=(a0*a21);
  a3=(a3*a0);
  a4=(a4*a19);
  a7=(a7*a4);
  a3=(a3+a7);
  a1=(a1-a3);
  a21=(a21*a1);
  a8=(a8+a21);
  if (res[1]!=0) res[1][20]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int nmpc_planner_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nmpc_planner_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nmpc_planner_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nmpc_planner_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nmpc_planner_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nmpc_planner_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nmpc_planner_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void nmpc_planner_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nmpc_planner_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int nmpc_planner_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nmpc_planner_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nmpc_planner_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nmpc_planner_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nmpc_planner_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nmpc_planner_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nmpc_planner_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
